development:
  arrays_dir: /Volumes/Arrays
  tiling_dir: /local/echidna_data/microarray/tiling 
  solr_url: http://localhost:8983/solr

test:
  arrays_dir: /Volumes/Arrays
  solr_url: http://localhost:8983/solr

production:
  arrays_dir: /net/arrays
  tiling_dir: /local/echidna_data/microarray/tiling 
  solr_url: http://bragi.systemsbiology.net:8081/solr
